spring:
  application:
    name: Plateforme_d-annotation_collaborative
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

file:
  upload-dir: uploads
